#!/bin/sh

basedir=$(pwd)

function _install_to_home_dir {
    echo "Installing to home dir"
    while read f
    do
        if [ -r "$f" ]
        then
            echo "  * $f"
            ln -sf $basedir/$1 ~
        fi
    done
}

function _install_launch_agents
{
    echo "Installing LaunchAgents"
    la_dir="LaunchAgents"
    for f in $(ls $la_dir); do
        echo "  * $f"
        ln -sf $basedir/$la_dir/$f ~/Library/LaunchAgents/
    done

}

_install_to_home_dir <<EOF
.spacemacs
.pydistutils.cfg
.zshenv
EOF

_install_launch_agents
