#!/bin/sh

basedir=$(pwd |sed "s@$HOME/@@")

# link file to home dir
function _link {
    echo "Linking $1 ... "
    ln -sf $basedir/$1 ~
}

function _link_all {
    while read f
    do
        if [ -r "$f" ]
        then
            _link $f
        fi
    done
}

echo "Current dir is $basedir"

_link_all <<EOF
.spacemacs
.pydistutils.cfg
.zshenv
EOF
